"""Simulate or implement the custom AXI DDR2 diagnostic for Nexys A7-50T."""
import argparse
import hashlib
import json
import os
from pathlib import Path
import re
import shutil
import subprocess
import sys
import xml.etree.ElementTree as ET

from test_mig import derive_configuration, tcl_path, text_hash, byte_hash

ROOT = Path(__file__).resolve().parents[1]
BUILDER = 'scripts/build_ddr_diag.py'
MIG_ROOT = 'project/axi_platform.gen/sources_1/bd/axi_ddr_bd/ip/axi_ddr_bd_mig_0/axi_ddr_bd_mig_0/'
MIG_TIMESTAMP_XDCS = tuple(MIG_ROOT + suffix for suffix in (
    'example_design/par/example_top.xdc',
    'user_design/constraints/axi_ddr_bd_mig_0.xdc',
    'user_design/constraints/axi_ddr_bd_mig_0_ooc.xdc'))
HASH_BASIS = 'raw_bytes_except_three_mig42_header_timestamps_v1'
MIG_TIMESTAMP = re.compile(
    rb'(?m)^(##  )((?:Mon|Tue|Wed|Thu|Fri|Sat|Sun) '
    rb'(?:Jan|Feb|Mar|Apr|May|Jun|Jul|Aug|Sep|Oct|Nov|Dec) '
    rb'[ \d]\d [0-2]\d:[0-5]\d:[0-5]\d \d{4})(\r?\n)')


def generated_file_hash(name, raw):
    """Ignore one generator date comment, never line endings or XDC commands."""
    if name in MIG_TIMESTAMP_XDCS:
        matches = list(MIG_TIMESTAMP.finditer(raw))
        header_end = 1024 if name.endswith('_ooc.xdc') else 512
        if (len(matches) != 1 or matches[0].end() > header_end or
                b'##  Generated by MIG Version 4.2' not in raw[:header_end]):
            raise ValueError(f'Unexpected MIG timestamp header: {name}')
        match = matches[0]
        raw = raw[:match.start(2)] + b'<MIG_TIMESTAMP>' + raw[match.end(2):]
    return hashlib.sha256(raw).hexdigest()


def generated_hash_metadata(out):
    return {'generated_hash_basis': HASH_BASIS,
            'generated_raw_mig_xdc_sha256': {name: byte_hash(out/name) for name in MIG_TIMESTAMP_XDCS}}


def input_files():
    return source_files() + [ROOT / name for name in (
        BUILDER, 'scripts/build_ddr_diag.tcl', 'scripts/create_axi_platform.tcl',
        'scripts/test_mig.py', 'tb/vendor/tb_ddr_platform.sv',
        'platform/nexys_a7/axi_ddr.xdc', 'platform/nexys_a7/ddr_diag.xdc',
        'accelerator nexys.srcs/sources_1/ip/mig_7series_0/mig_a.prj')]


def source_files():
    return [ROOT / name for name in (
        'rtl/memory/gemm_axi_burst.sv', 'rtl/control/gemm_ddr_diag.sv',
        'rtl/control/gemm_ddr_diag_control.sv', 'rtl/control/gemm_packet_transport.sv',
        'accelerator nexys.srcs/sources_1/new/uart_rx.sv',
        'accelerator nexys.srcs/sources_1/new/uart_tx.sv',
        'platform/nexys_a7/axi_ddr_platform.sv', 'platform/nexys_a7/gemm_ddr_diag_top.sv')]


def generated_hashes(out):
    """Bind implementation to the generated RTL/configuration actually simulated."""
    suffixes = {'.v', '.sv', '.vh', '.svh', '.vhd', '.vhdl', '.xdc', '.bd', '.xci', '.prj', '.mem', '.coe'}
    paths = [out / 'mig_axi.prj']
    for folder in ('axi_platform.srcs', 'axi_platform.gen', 'axi_platform.ip_user_files', 'imports'):
        paths.extend(p for p in (out / 'project' / folder).rglob('*')
                     if p.is_file() and p.suffix.lower() in suffixes)
    if not any(p.suffix == '.bd' for p in paths):
        raise RuntimeError('Generated platform block design is missing')
    return {p.relative_to(out).as_posix(): generated_file_hash(p.relative_to(out).as_posix(), p.read_bytes())
            for p in sorted(paths)}


def platform_configuration():
    xml, pins = derive_configuration()
    platform_xml = ET.fromstring(xml)
    platform_xml.find('Controller/AXIParameters/C0_S_AXI_SUPPORTS_NARROW_BURST').text = '0'
    return ET.tostring(platform_xml, encoding='unicode') + '\n', pins


def verify_timestamp_changes(out, simulated, proof):
    """Reconstruct the exact old bytes; canonical equality alone is insufficient."""
    if len(proof) != 3 or {item['path'] for item in proof} != set(MIG_TIMESTAMP_XDCS):
        raise ValueError('Expected proof for exactly the three generated MIG XDC headers')
    canonical = dict(simulated)
    for item in proof:
        name = item['path']
        raw = (out/name).read_bytes()
        if (byte_hash(out/name) != item['actual_raw_after_sha256'] or
                simulated[name] != item['exact_raw_before_sha256']):
            raise ValueError(f'Timestamp proof raw hashes do not match: {name}')
        match = MIG_TIMESTAMP.search(raw)
        if not match or not re.fullmatch(r'[0-2]\d:[0-5]\d:[0-5]\d', item['before_timestamp']):
            raise ValueError(f'Invalid timestamp reconstruction: {name}')
        timestamp = match.group(2)
        if timestamp.count(item['after_timestamp'].encode('ascii')) != 1:
            raise ValueError(f'Unexpected current timestamp: {name}')
        before = (raw[:match.start(2)] + timestamp.replace(item['after_timestamp'].encode('ascii'),
                  item['before_timestamp'].encode('ascii')) + raw[match.end(2):])
        if hashlib.sha256(before).hexdigest() != simulated[name]:
            raise ValueError(f'Change extends beyond the proven timestamp: {name}')
        canonical[name] = generated_file_hash(name, before)
    if canonical != generated_hashes(out):
        raise ValueError('Generated RTL, constraints or configuration differ from simulation')
    return canonical


def verify_existing(out, archive, proof_path):
    """Qualify an already routed run without changing its original failure record."""
    (out/'build.json').unlink(missing_ok=True)
    protected = [out/name for name in ('inputs.json', 'simulation.json', 'bitstream_exit.txt',
                 'bitstream_runner.txt', 'bitstream_console.txt', 'timing_pass.json',
                 'gemm_ddr_diag.bit', 'project/axi_platform.xpr')]
    protected += [archive, proof_path, Path(__file__)]
    before = {path: byte_hash(path) for path in protected}
    identity = json.loads((out/'inputs.json').read_text())
    passed = json.loads((out/'simulation.json').read_text())
    hashes = identity['source_sha256_utf8_lf']
    if (set(hashes) != {p.relative_to(ROOT).as_posix() for p in input_files()} or
            passed['result'] != 'PASS' or passed['source_sha256_utf8_lf'] != hashes or
            any(passed[key] != identity[key] for key in ('part','baud','core_hz','build_id'))):
        raise ValueError('Original simulation and complete source identity do not match')
    checked = {name: text_hash(archive if name == BUILDER else ROOT/name) for name in hashes}
    if checked != hashes:
        raise ValueError('As-built builder archive or another build input changed')
    calculated = int.from_bytes(hashlib.sha256(json.dumps(
        {key:value for key,value in identity.items() if key != 'build_id'},
        sort_keys=True).encode()).digest()[:4], 'little')
    if calculated != identity['build_id']:
        raise ValueError('As-built BUILD_ID does not match its source/configuration identity')
    if ((out/'bitstream_exit.txt').read_text().strip() != '1' or
            'Generated platform changed during implementation' not in (out/'bitstream_runner.txt').read_text()):
        raise ValueError('This verification step requires the recorded provenance-gate failure')
    proof = json.loads(proof_path.read_text())
    generated = verify_timestamp_changes(out, passed['generated_sha256'], proof)
    xml, pins = platform_configuration()
    validate_platform(out, xml, pins)
    console = out/'bitstream_console.txt'
    log = console.read_text(encoding='utf-8')
    checks = json.loads((out/'timing_pass.json').read_text())
    marker = re.search(r'DDR_DIAG_BUILD_PASS WNS=([\d.]+) WHS=([\d.]+)', log)
    if (not marker or re.search(r'ERROR:|FATAL:|Fatal:|CRITICAL WARNING:', log) or
            'Bitgen Completed Successfully' not in log or
            tuple(map(float, marker.groups())) != (checks['wns_ns'], checks['whs_ns']) or
            checks['core_hz'] != identity['core_hz'] or
            'All user specified timing constraints are met.' not in (out/'timing.txt').read_text()):
        raise ValueError('Original Vivado timing/bitstream completion is not valid')
    skew = (out/'bus_skew.txt').read_text().split(
        '\n2. Bus Skew Report Per Constraint\n---------------------------------',1)[0]
    slacks = re.findall(r'^\s+(?:Slow|Fast)\s+[\d.]+\s+[\d.]+\s+(-?[\d.]+)\s*$',skew,re.M)
    if len(slacks) != 10 or min(map(float,slacks)) < 0:
        raise ValueError('Bus-skew constraints did not all pass')
    metadata = {'result':'PASS', 'method':'Exact raw-byte reconstruction of three MIG timestamp comments',
        'verifier_sha256_utf8_lf':text_hash(Path(__file__)),
        'as_built_builder_sha256_utf8_lf':text_hash(archive),
        'original_runner_exit_code':1, 'original_runner_log_sha256_bytes':byte_hash(out/'bitstream_runner.txt'),
        'original_console_sha256_bytes':byte_hash(console),
        'timestamp_proof_sha256_bytes':byte_hash(proof_path), 'timestamp_changes':proof,
        'simulation_summary_sha256_bytes':byte_hash(out/'simulation.json'),
        'all_other_source_inputs_unchanged':True, 'all_other_generated_files_unchanged':True}
    manifest = dict(identity, schema_version=1, result='PASS',
        source_commit=passed['source_commit'], source_dirty=passed['source_dirty'],
        generated_sha256=generated, **generated_hash_metadata(out),
        project_sha256=byte_hash(out/'project/axi_platform.xpr'), ddr_pins_preserved=len(pins),
        configuration_sha256_utf8_lf=text_hash(out/'mig_axi.prj'), console_sha256_utf8_lf=text_hash(console),
        bitstream='gemm_ddr_diag.bit', bitstream_sha256=byte_hash(out/'gemm_ddr_diag.bit'),
        scope='AXI DDR2 memory diagnostic; GEMM not connected', physical_checks=checks,
        verification=metadata)
    if (any(byte_hash(path) != digest for path,digest in before.items()) or
            generated != generated_hashes(out) or
            checked != {name:text_hash(archive if name == BUILDER else ROOT/name) for name in hashes}):
        raise RuntimeError('Evidence changed during explicit verification')
    (out/'verification.json').write_text(json.dumps(metadata,indent=2)+'\n',encoding='utf-8')
    (out/'build.json').write_text(json.dumps(manifest,indent=2)+'\n',encoding='utf-8')
    print(f'PASS: explicit verification; original build exit 1 retained; {out / "build.json"}',flush=True)


def validate_platform(out, xml, pins):
    prj = out / 'mig_axi.prj'
    # Verify that generated MIG retains the saved physical map and memory size.
    mig_xcis = []
    for path in (out / 'project').rglob('*.xci'):
        data = json.loads(path.read_text())['ip_inst']
        if data['component_reference'] == 'xilinx.com:ip:mig_7series:4.2':
            mig_xcis.append((path, data))
    if len(mig_xcis) != 1:
        raise RuntimeError('Expected one generated MIG configuration')
    xci_path, xci = mig_xcis[0]
    configured = xci['parameters']['component_parameters']['XML_INPUT_FILE'][0]['value']
    if (xci_path.parent / configured).resolve() != prj.resolve():
        raise RuntimeError('Generated MIG refers to a different memory configuration')
    params = xci['parameters']['model_parameters']
    required = {'USE_AXI': '1', 'MEM_TYPE': 'DDR2', 'C_S_AXI_ADDR_WIDTH': '27',
                'C_S_AXI_DATA_WIDTH': '128', 'C_S_AXI_MEM_SIZE': '134217728',
                'DDR2_nCK_PER_CLK': '4', 'SYSCLK_TYPE': 'NOBUF', 'REFCLK_TYPE': 'NOBUF'}
    if any(params[name][0]['value'] != value for name, value in required.items()):
        raise RuntimeError('Generated MIG has unexpected bus/memory settings')
    if prj.read_text(encoding='utf-8') != xml:
        raise RuntimeError('Vivado changed the intended platform MIG configuration')
    mig_rtl = [p for p in (out / 'project/axi_platform.gen').rglob('*.v')
               if p.name.endswith(('_mig.v', '_mig_sim.v'))]
    if len(mig_rtl) != 2 or any(not re.search(
            r'parameter\s+C_S_AXI_SUPPORTS_NARROW_BURST\s*=\s*0\s*,',
            p.read_text()) for p in mig_rtl):
        raise RuntimeError('Generated MIG narrow-burst implementation differs from the platform configuration')
    xdc_files = list((out / 'project/axi_platform.gen').rglob('*mig*.xdc'))
    checked_pins = False
    for path in xdc_files:
        constraints = path.read_text()
        assignments = dict((port, value) for value, port in re.findall(
            r'^set_property PACKAGE_PIN\s+(\S+)\s+\[get_ports\s+\{(ddr2_[^}]+)\}',
            constraints, re.MULTILINE))
        if len(assignments) == len(pins):
            if assignments != {name: pin['PADName'] for name, pin in pins.items()}:
                raise RuntimeError('Generated DDR pin map differs from the saved board')
            standards = dict((port, value) for value, port in re.findall(
                r'^set_property IOSTANDARD\s+(\S+)\s+\[get_ports\s+\{(ddr2_[^}]+)\}',
                constraints, re.MULTILINE))
            if standards != {name: pin['IOSTANDARD'] for name, pin in pins.items()}:
                raise RuntimeError('Generated DDR I/O standards differ from the saved board')
            checked_pins = True
    if not checked_pins:
        raise RuntimeError('Could not verify generated DDR pin map')


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--stage', choices=('sim', 'bitstream', 'verify'), default='sim')
    parser.add_argument('--as-built-builder', type=Path,
                        help='Archived original builder for explicit verification of an existing run')
    parser.add_argument('--timestamp-proof', type=Path,
                        help='Exact before/after raw hash and timestamp proof for three generated MIG XDC files')
    parser.add_argument('--warm-reset', action='store_true',
                        help='Also qualify abrupt controller reset against the unchanged DDR model (simulation only)')
    parser.add_argument('--build-dir', type=Path, default=ROOT / 'build/ddr_diag')
    parser.add_argument('--vivado', default=shutil.which('vivado') or
                        'C:/AMDDesignTools/2026.1/Vivado/bin/vivado.bat')
    args = parser.parse_args()
    if args.warm_reset and args.stage != 'sim':
        parser.error('--warm-reset is a simulation qualification, not a bitstream option')
    out = args.build_dir.resolve()
    out.mkdir(parents=True, exist_ok=True)
    if args.stage == 'verify':
        if args.as_built_builder is None or args.timestamp_proof is None:
            parser.error('--stage verify requires --as-built-builder and --timestamp-proof')
        verify_existing(out, args.as_built_builder.resolve(), args.timestamp_proof.resolve())
        return
    if args.as_built_builder is not None or args.timestamp_proof is not None:
        parser.error('Verification evidence options require --stage verify')
    stale = ('simulation.json', 'simulation_complete.txt', 'build.json') if args.stage == 'sim' else (
        'build.json', 'timing_pass.json', 'gemm_ddr_diag.bit')
    for name in stale:
        (out / name).unlink(missing_ok=True)
    sources = source_files()
    inputs = input_files()
    hashes = {p.relative_to(ROOT).as_posix(): text_hash(p) for p in inputs}
    project_file = out / 'project/axi_platform.xpr'
    generation_state = out / 'generated_state.json'
    previous_generation = None
    if args.stage == 'sim' and project_file.exists():
        if not generation_state.exists():
            raise ValueError('Unsealed existing project; use a fresh --build-dir')
        previous_generation = json.loads(generation_state.read_text())
        if (previous_generation['source_sha256_utf8_lf'] != hashes or
                previous_generation['generated_sha256'] != generated_hashes(out) or
                previous_generation['project_sha256'] != byte_hash(project_file)):
            raise ValueError('Existing project/sources changed; use a fresh --build-dir')
    identity = {'source_sha256_utf8_lf': hashes, 'part': 'xc7a50ticsg324-1L',
                'baud': 115200, 'core_hz': 100000000}
    build_id = int.from_bytes(hashlib.sha256(json.dumps(identity, sort_keys=True).encode()).digest()[:4], 'little')
    xml, pins = platform_configuration()
    # SmartConnect packs multi-beat traffic to 128 bits. Its propagated MIG
    # capability disables narrow bursts; single narrow beats remain supported.
    # Keep the standalone MIG test's narrow-enabled configuration unchanged.
    prj = out / 'mig_axi.prj'
    if prj.exists() and prj.read_text(encoding='utf-8') != xml:
        raise ValueError('MIG configuration changed; use a fresh --build-dir')
    prj.write_text(xml, encoding='utf-8')
    simulation = out / 'simulation.json'
    if args.stage == 'bitstream':
        if not simulation.exists():
            raise ValueError('Run --stage sim successfully before building a bitstream')
        passed = json.loads(simulation.read_text())
        if passed['result'] != 'PASS' or passed['source_sha256_utf8_lf'] != hashes:
            raise ValueError('Simulation does not match these sources; rerun --stage sim')
        if passed['generated_sha256'] != generated_hashes(out):
            raise ValueError('Generated platform changed after simulation; use a fresh --build-dir')
        if passed['project_sha256'] != byte_hash(project_file):
            raise ValueError('Vivado project changed after simulation; use a fresh --build-dir')
    config = out / 'config.tcl'
    config.write_text('\n'.join([
        f'set ddr_root {tcl_path(ROOT)}', f'set ddr_out {tcl_path(out)}',
        f'set ddr_stage {args.stage}', f'set ddr_build_id {build_id}',
        f'set ddr_warm_reset {int(args.warm_reset)}',
        f'set ddr_sources [list {" ".join(tcl_path(p) for p in sources)}]', '']), encoding='utf-8')
    (out / 'inputs.json').write_text(json.dumps(dict(identity, build_id=build_id), indent=2)+'\n', encoding='utf-8')
    console = out / f'{args.stage}_console.txt'
    command = [args.vivado, '-mode', 'batch', '-notrace', '-source',
               str(ROOT / 'scripts/build_ddr_diag.tcl'), '-log', str(out / f'{args.stage}.log'),
               '-journal', str(out / f'{args.stage}.jou'), '-tclargs', str(config)]
    kwargs = {'creationflags': subprocess.CREATE_NO_WINDOW} if os.name == 'nt' else {}
    print(f'DDR diagnostic {args.stage}; build ID 0x{build_id:08x}; logs: {console}', flush=True)
    with console.open('w', encoding='utf-8') as log:
        result = subprocess.run(command, cwd=out, stdout=log, stderr=subprocess.STDOUT, **kwargs)
    log = console.read_text(encoding='utf-8', errors='replace')
    if any(text_hash(ROOT / name) != digest for name, digest in hashes.items()):
        raise RuntimeError('Sources changed during the run; rerun before recording results')
    # Preserve a seal after complete IP generation even if compilation fails.
    # A retry may reuse only the exact project and generated inputs, never a
    # project whose GUI settings or generator sources have since changed.
    if args.stage == 'sim' and (previous_generation or 'AXI_DDR_PLATFORM_GENERATED ' in log):
        current_generated = generated_hashes(out)
        if previous_generation and current_generated != previous_generation['generated_sha256']:
            raise RuntimeError('Generated platform changed during simulation retry')
        generation_state.write_text(json.dumps(dict(
            source_sha256_utf8_lf=hashes, generated_sha256=current_generated,
            project_sha256=byte_hash(project_file), **generated_hash_metadata(out)), indent=2)+'\n', encoding='utf-8')
    if result.returncode or re.search(r'ERROR:|FATAL:|Fatal:|CRITICAL WARNING:', log):
        raise RuntimeError(f'Vivado {args.stage} failed; inspect {console}')
    generated = generated_hashes(out)
    if args.stage == 'bitstream' and generated != passed['generated_sha256']:
        raise RuntimeError('Generated platform changed during implementation; repeat simulation in a fresh directory')
    validate_platform(out, xml, pins)
    git = lambda *cmd: subprocess.check_output(['git', '-C', str(ROOT), *cmd], text=True).strip()
    common = dict(identity, schema_version=1, build_id=build_id, source_commit=git('rev-parse', 'HEAD'),
                  source_dirty=bool(git('status', '--porcelain')), result='PASS',
                  generated_sha256=generated,
                  **generated_hash_metadata(out),
                  project_sha256=byte_hash(project_file),
                  ddr_pins_preserved=len(pins), configuration_sha256_utf8_lf=text_hash(prj),
                  console_sha256_utf8_lf=text_hash(console))
    if args.stage == 'sim':
        match = re.search(r'DDR_PLATFORM_PASS runs=(\d+) read_beats=(\d+) write_beats=(\d+) write_responses=(\d+)', log)
        if (not match or 'DDR_DECODE_PASS' not in log or 'DDR_SINGLE_READ_PASS' not in log or
                not (out / 'simulation_complete.txt').exists()):
            raise RuntimeError('Missing complete platform simulation evidence')
        if args.warm_reset and 'DDR_RESET_FUNCTIONAL_PASS' not in log:
            raise RuntimeError('Missing warm-reset functional recovery evidence')
        summary = dict(common, scope='Custom burst engine + SmartConnect + MIG + vendor DDR2 model; no physical-board claim',
                       traffic=dict(zip(('runs', 'read_beats', 'write_beats', 'write_responses'), map(int, match.groups()))),
                       warm_reset_qualified=args.warm_reset,
                       calibration='FAST', physical_pcb_delays=False,
                       vivado=(out / 'simulation_complete.txt').read_text().strip())
        simulation.write_text(json.dumps(summary, indent=2)+'\n', encoding='utf-8')
        print(f'PASS: {simulation}', flush=True)
    else:
        checks = out / 'timing_pass.json'
        bitstream = out / 'gemm_ddr_diag.bit'
        if not checks.exists() or not bitstream.exists():
            raise RuntimeError('Missing timing gates or bitstream')
        manifest = dict(common, bitstream=bitstream.name, bitstream_sha256=byte_hash(bitstream),
                        scope='AXI DDR2 memory diagnostic; GEMM not connected',
                        physical_checks=json.loads(checks.read_text()))
        (out / 'build.json').write_text(json.dumps(manifest, indent=2)+'\n', encoding='utf-8')
        print(f'PASS: {out / "build.json"}', flush=True)


if __name__ == '__main__':
    try:
        main()
    except (OSError, ValueError, RuntimeError, subprocess.SubprocessError) as exc:
        print(str(exc), file=sys.stderr)
        sys.exit(1)
