"""Keep generated-header tolerance narrower than executable build inputs."""
import hashlib
import importlib.util
import json
from pathlib import Path
import sys
import tempfile
import unittest
from unittest.mock import patch

SCRIPTS = Path(__file__).resolve().parents[1] / 'scripts'
sys.path.insert(0, str(SCRIPTS))
spec = importlib.util.spec_from_file_location('ddr_builder', SCRIPTS/'build_ddr_diag.py')
builder = importlib.util.module_from_spec(spec)
spec.loader.exec_module(builder)

HEADER = (b'##################################################################\r\r\n'
          b'##  Fri Oct  2 15:37:13 2026\r\n'
          b'##  Generated by MIG Version 4.2\r\r\n')
BODY = b'set_property PACKAGE_PIN R2 [get_ports {ddr2_dq[0]}]\r\r\nset_false_path -from [get_ports reset]\r\n'


class GeneratedFingerprintTests(unittest.TestCase):
    def test_only_known_header_timestamp_is_ignored(self):
        old = HEADER + BODY
        new = old.replace(b'15:37:13', b'15:52:15')
        for name in builder.MIG_TIMESTAMP_XDCS:
            self.assertEqual(builder.generated_file_hash(name, old), builder.generated_file_hash(name, new))
        for name in ('other.xdc', 'rtl/module.sv', builder.MIG_TIMESTAMP_XDCS[0] + '.copy'):
            self.assertNotEqual(builder.generated_file_hash(name, old), builder.generated_file_hash(name, new))

    def test_constraints_pins_newlines_and_extra_comments_remain_significant(self):
        name = builder.MIG_TIMESTAMP_XDCS[0]
        raw = HEADER + BODY
        baseline = builder.generated_file_hash(name, raw)
        for changed in (raw.replace(b'R2',b'R3'), raw.replace(b'set_false_path',b'set_max_delay 1'),
                        raw.replace(b'\r\r\n',b'\n'),raw+b'# another comment\n'):
            self.assertNotEqual(baseline, builder.generated_file_hash(name, changed))

    def test_malformed_or_duplicated_header_fails_closed(self):
        name = builder.MIG_TIMESTAMP_XDCS[0]
        for raw in (BODY, HEADER+HEADER+BODY, HEADER.replace(b'4.2',b'4.3')+BODY,
                    b'#'+b'x'*1100+b'\n'+HEADER+BODY):
            with self.assertRaises(ValueError):
                builder.generated_file_hash(name, raw)

    def proof_fixture(self, out):
        old = HEADER + BODY
        new = old.replace(b'15:37:13',b'15:52:15')
        digest = lambda b:hashlib.sha256(b).hexdigest()
        proof = []
        baseline = {'unrelated.sv':digest(b'module x; endmodule\n')}
        current = dict(baseline)
        for name in builder.MIG_TIMESTAMP_XDCS:
            (out/name).parent.mkdir(parents=True,exist_ok=True)
            (out/name).write_bytes(new)
            baseline[name] = digest(old)
            current[name] = builder.generated_file_hash(name,new)
            proof.append({'path':name,'exact_raw_before_sha256':digest(old),
                          'actual_raw_after_sha256':digest(new),
                          'before_timestamp':'15:37:13','after_timestamp':'15:52:15'})
        return baseline,current,proof

    def test_reconstruction_checks_original_raw_bytes_and_other_generated_files(self):
        with tempfile.TemporaryDirectory() as temp:
            out = Path(temp)
            baseline,current,proof = self.proof_fixture(out)
            with patch.object(builder,'generated_hashes',return_value=current):
                self.assertEqual(builder.verify_timestamp_changes(out,baseline,proof),current)
                altered = [dict(item) for item in proof]
                altered[0]['before_timestamp'] = '15:37:14'
                with self.assertRaises(ValueError):
                    builder.verify_timestamp_changes(out,baseline,altered)
                altered = [dict(item) for item in proof]
                altered[0]['exact_raw_before_sha256'] = '0'*64
                with self.assertRaises(ValueError):
                    builder.verify_timestamp_changes(out,baseline,altered)
            with patch.object(builder,'generated_hashes',return_value=dict(current,**{'unrelated.sv':'0'*64})):
                with self.assertRaises(ValueError):
                    builder.verify_timestamp_changes(out,baseline,proof)
            name = builder.MIG_TIMESTAMP_XDCS[0]
            (out/name).write_bytes((out/name).read_bytes().replace(b'R2',b'R3'))
            with self.assertRaises(ValueError):
                builder.verify_timestamp_changes(out,baseline,proof)

    def test_proof_cannot_expand_file_allowlist(self):
        with tempfile.TemporaryDirectory() as temp:
            out = Path(temp)
            baseline,current,proof = self.proof_fixture(out)
            for invalid in (proof[:2], proof+[dict(proof[0])], [dict(p,path='other.xdc') for p in proof]):
                with self.assertRaises(ValueError):
                    builder.verify_timestamp_changes(out,baseline,invalid)

    def test_existing_verification_rejects_changed_nonbuilder_input(self):
        with tempfile.TemporaryDirectory() as temp:
            root = Path(temp)
            out = root/'build'
            out.mkdir()
            original_source = root/'design.sv'
            original_source.write_text('original design\n')
            archive = out/'builder.py'
            archive.write_text('original builder\n')
            proof = out/'proof.json'
            proof.write_text('[]')
            hashes = {'design.sv':builder.text_hash(original_source),
                      builder.BUILDER:builder.text_hash(archive)}
            identity = {'source_sha256_utf8_lf':hashes,'part':'part','baud':115200,'core_hz':100000000,'build_id':1}
            (out/'inputs.json').write_text(json.dumps(identity))
            (out/'simulation.json').write_text(json.dumps(dict(identity,result='PASS')))
            for name in ('bitstream_exit.txt','bitstream_runner.txt','bitstream_console.txt',
                         'timing_pass.json','gemm_ddr_diag.bit','project/axi_platform.xpr'):
                p=out/name
                p.parent.mkdir(parents=True,exist_ok=True)
                p.write_bytes(b'fixture')
            original_source.write_text('changed design\n')
            with patch.object(builder,'ROOT',root), patch.object(builder,'input_files',
                    return_value=[original_source,root/builder.BUILDER]):
                with self.assertRaisesRegex(ValueError,'another build input changed'):
                    builder.verify_existing(out,archive,proof)
            self.assertFalse((out/'build.json').exists())


if __name__ == '__main__':
    unittest.main()
